# Generated by Django 4.2.3 on 2023-07-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPersonalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=10)),
                ('user_first_name', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=50, null=True)),
                ('user_status', models.CharField(default='user', max_length=6)),
                ('user_active', models.BooleanField(default=False)),
                ('data_time_create', models.DateTimeField(auto_now_add=True)),
                ('data_time_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
