# Generated by Django 4.2.3 on 2023-07-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Telegram_bot_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpersonaldata',
            name='user_active',
            field=models.BooleanField(default=True),
        ),
    ]
