# Generated by Django 4.2.3 on 2023-07-25 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Telegram_bot_backend', '0002_alter_userpersonaldata_user_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersRunningTrainingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('finish_time', models.DateTimeField(blank=True, null=True)),
                ('running_time', models.DurationField(blank=True, null=True)),
                ('route_coordinates', models.JSONField(blank=True, null=True)),
                ('route_length', models.FloatField(blank=True, null=True)),
                ('route_map', models.FileField(blank=True, null=True, upload_to='_all_file/user_file/route_maps/%Y/%m/%d/<django.db.models.fields.related.ForeignKey>/%H_%M_%S')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Telegram_bot_backend.userpersonaldata')),
            ],
        ),
    ]
