# Generated by Django 4.2.3 on 2023-07-25 20:47

import Telegram_bot_backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Telegram_bot_backend', '0003_usersrunningtrainingdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersrunningtrainingdata',
            name='route_map',
            field=models.FileField(blank=True, null=True, upload_to=Telegram_bot_backend.models.user_route_map_upload_path),
        ),
    ]
