# Generated by Django 4.2.3 on 2023-07-26 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Telegram_bot_backend', '0004_alter_usersrunningtrainingdata_route_map'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersrunningtrainingdata',
            old_name='user_id',
            new_name='user',
        ),
    ]
